// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cropmanagementservice.proto

package com.example.smartagritest;

public interface AddCropRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.AddCropRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 quantity = 3;</code>
   */
  int getQuantity();
}
