// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livestockmanagement.proto

package com.example.smartagritest;

/**
 * Protobuf type {@code com.example.smartagritest.AddLiveStockRequest}
 */
public  final class AddLiveStockRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.smartagritest.AddLiveStockRequest)
    AddLiveStockRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddLiveStockRequest.newBuilder() to construct.
  private AddLiveStockRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddLiveStockRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddLiveStockRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.example.smartagritest.LiveStock.Builder subBuilder = null;
            if (liveStock_ != null) {
              subBuilder = liveStock_.toBuilder();
            }
            liveStock_ = input.readMessage(com.example.smartagritest.LiveStock.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(liveStock_);
              liveStock_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.smartagritest.LiveStockManagementProto.internal_static_com_example_smartagritest_AddLiveStockRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.smartagritest.LiveStockManagementProto.internal_static_com_example_smartagritest_AddLiveStockRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.smartagritest.AddLiveStockRequest.class, com.example.smartagritest.AddLiveStockRequest.Builder.class);
  }

  public static final int LIVESTOCK_FIELD_NUMBER = 1;
  private com.example.smartagritest.LiveStock liveStock_;
  /**
   * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
   */
  public boolean hasLiveStock() {
    return liveStock_ != null;
  }
  /**
   * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
   */
  public com.example.smartagritest.LiveStock getLiveStock() {
    return liveStock_ == null ? com.example.smartagritest.LiveStock.getDefaultInstance() : liveStock_;
  }
  /**
   * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
   */
  public com.example.smartagritest.LiveStockOrBuilder getLiveStockOrBuilder() {
    return getLiveStock();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (liveStock_ != null) {
      output.writeMessage(1, getLiveStock());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (liveStock_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLiveStock());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.smartagritest.AddLiveStockRequest)) {
      return super.equals(obj);
    }
    com.example.smartagritest.AddLiveStockRequest other = (com.example.smartagritest.AddLiveStockRequest) obj;

    boolean result = true;
    result = result && (hasLiveStock() == other.hasLiveStock());
    if (hasLiveStock()) {
      result = result && getLiveStock()
          .equals(other.getLiveStock());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLiveStock()) {
      hash = (37 * hash) + LIVESTOCK_FIELD_NUMBER;
      hash = (53 * hash) + getLiveStock().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.smartagritest.AddLiveStockRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.AddLiveStockRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.smartagritest.AddLiveStockRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.smartagritest.AddLiveStockRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.smartagritest.AddLiveStockRequest)
      com.example.smartagritest.AddLiveStockRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.smartagritest.LiveStockManagementProto.internal_static_com_example_smartagritest_AddLiveStockRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.smartagritest.LiveStockManagementProto.internal_static_com_example_smartagritest_AddLiveStockRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.smartagritest.AddLiveStockRequest.class, com.example.smartagritest.AddLiveStockRequest.Builder.class);
    }

    // Construct using com.example.smartagritest.AddLiveStockRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (liveStockBuilder_ == null) {
        liveStock_ = null;
      } else {
        liveStock_ = null;
        liveStockBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.smartagritest.LiveStockManagementProto.internal_static_com_example_smartagritest_AddLiveStockRequest_descriptor;
    }

    @java.lang.Override
    public com.example.smartagritest.AddLiveStockRequest getDefaultInstanceForType() {
      return com.example.smartagritest.AddLiveStockRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.smartagritest.AddLiveStockRequest build() {
      com.example.smartagritest.AddLiveStockRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.smartagritest.AddLiveStockRequest buildPartial() {
      com.example.smartagritest.AddLiveStockRequest result = new com.example.smartagritest.AddLiveStockRequest(this);
      if (liveStockBuilder_ == null) {
        result.liveStock_ = liveStock_;
      } else {
        result.liveStock_ = liveStockBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.smartagritest.AddLiveStockRequest) {
        return mergeFrom((com.example.smartagritest.AddLiveStockRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.smartagritest.AddLiveStockRequest other) {
      if (other == com.example.smartagritest.AddLiveStockRequest.getDefaultInstance()) return this;
      if (other.hasLiveStock()) {
        mergeLiveStock(other.getLiveStock());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.smartagritest.AddLiveStockRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.smartagritest.AddLiveStockRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.smartagritest.LiveStock liveStock_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.smartagritest.LiveStock, com.example.smartagritest.LiveStock.Builder, com.example.smartagritest.LiveStockOrBuilder> liveStockBuilder_;
    /**
     * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
     */
    public boolean hasLiveStock() {
      return liveStockBuilder_ != null || liveStock_ != null;
    }
    /**
     * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
     */
    public com.example.smartagritest.LiveStock getLiveStock() {
      if (liveStockBuilder_ == null) {
        return liveStock_ == null ? com.example.smartagritest.LiveStock.getDefaultInstance() : liveStock_;
      } else {
        return liveStockBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
     */
    public Builder setLiveStock(com.example.smartagritest.LiveStock value) {
      if (liveStockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        liveStock_ = value;
        onChanged();
      } else {
        liveStockBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
     */
    public Builder setLiveStock(
        com.example.smartagritest.LiveStock.Builder builderForValue) {
      if (liveStockBuilder_ == null) {
        liveStock_ = builderForValue.build();
        onChanged();
      } else {
        liveStockBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
     */
    public Builder mergeLiveStock(com.example.smartagritest.LiveStock value) {
      if (liveStockBuilder_ == null) {
        if (liveStock_ != null) {
          liveStock_ =
            com.example.smartagritest.LiveStock.newBuilder(liveStock_).mergeFrom(value).buildPartial();
        } else {
          liveStock_ = value;
        }
        onChanged();
      } else {
        liveStockBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
     */
    public Builder clearLiveStock() {
      if (liveStockBuilder_ == null) {
        liveStock_ = null;
        onChanged();
      } else {
        liveStock_ = null;
        liveStockBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
     */
    public com.example.smartagritest.LiveStock.Builder getLiveStockBuilder() {
      
      onChanged();
      return getLiveStockFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
     */
    public com.example.smartagritest.LiveStockOrBuilder getLiveStockOrBuilder() {
      if (liveStockBuilder_ != null) {
        return liveStockBuilder_.getMessageOrBuilder();
      } else {
        return liveStock_ == null ?
            com.example.smartagritest.LiveStock.getDefaultInstance() : liveStock_;
      }
    }
    /**
     * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.smartagritest.LiveStock, com.example.smartagritest.LiveStock.Builder, com.example.smartagritest.LiveStockOrBuilder> 
        getLiveStockFieldBuilder() {
      if (liveStockBuilder_ == null) {
        liveStockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.smartagritest.LiveStock, com.example.smartagritest.LiveStock.Builder, com.example.smartagritest.LiveStockOrBuilder>(
                getLiveStock(),
                getParentForChildren(),
                isClean());
        liveStock_ = null;
      }
      return liveStockBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.smartagritest.AddLiveStockRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.smartagritest.AddLiveStockRequest)
  private static final com.example.smartagritest.AddLiveStockRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.smartagritest.AddLiveStockRequest();
  }

  public static com.example.smartagritest.AddLiveStockRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddLiveStockRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddLiveStockRequest>() {
    @java.lang.Override
    public AddLiveStockRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddLiveStockRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddLiveStockRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddLiveStockRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.smartagritest.AddLiveStockRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

