// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public interface AlertThresholdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.AlertThreshold)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_name = 1;</code>
   */
  java.lang.String getSensorName();
  /**
   * <code>string sensor_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorNameBytes();

  /**
   * <code>double threshold = 2;</code>
   */
  double getThreshold();
}
