// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livestockmanagement.proto

package com.example.smartagritest;

public interface FeedLiveStockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.FeedLiveStockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double amount = 2;</code>
   */
  double getAmount();
}
