// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cropmanagementservice.proto

package com.example.smartagritest;

public interface HarvestCropRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.HarvestCropRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string harvesting_date = 2;</code>
   */
  java.lang.String getHarvestingDate();
  /**
   * <code>string harvesting_date = 2;</code>
   */
  com.google.protobuf.ByteString
      getHarvestingDateBytes();
}
