// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public interface HumidityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.HumidityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_name = 1;</code>
   */
  java.lang.String getSensorName();
  /**
   * <code>string sensor_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorNameBytes();
}
