// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public interface HumidityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.HumidityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
   */
  boolean hasHumidityReading();
  /**
   * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
   */
  com.example.smartagritest.HumidityReading getHumidityReading();
  /**
   * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
   */
  com.example.smartagritest.HumidityReadingOrBuilder getHumidityReadingOrBuilder();
}
