// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public interface HumidityReadingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.HumidityReading)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double humidity = 1;</code>
   */
  double getHumidity();

  /**
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();
}
