// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

/**
 * Protobuf type {@code com.example.smartagritest.HumidityResponse}
 */
public  final class HumidityResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.smartagritest.HumidityResponse)
    HumidityResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HumidityResponse.newBuilder() to construct.
  private HumidityResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HumidityResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HumidityResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.example.smartagritest.HumidityReading.Builder subBuilder = null;
            if (humidityReading_ != null) {
              subBuilder = humidityReading_.toBuilder();
            }
            humidityReading_ = input.readMessage(com.example.smartagritest.HumidityReading.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(humidityReading_);
              humidityReading_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_HumidityResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_HumidityResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.smartagritest.HumidityResponse.class, com.example.smartagritest.HumidityResponse.Builder.class);
  }

  public static final int HUMIDITY_READING_FIELD_NUMBER = 1;
  private com.example.smartagritest.HumidityReading humidityReading_;
  /**
   * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
   */
  public boolean hasHumidityReading() {
    return humidityReading_ != null;
  }
  /**
   * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
   */
  public com.example.smartagritest.HumidityReading getHumidityReading() {
    return humidityReading_ == null ? com.example.smartagritest.HumidityReading.getDefaultInstance() : humidityReading_;
  }
  /**
   * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
   */
  public com.example.smartagritest.HumidityReadingOrBuilder getHumidityReadingOrBuilder() {
    return getHumidityReading();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (humidityReading_ != null) {
      output.writeMessage(1, getHumidityReading());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (humidityReading_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHumidityReading());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.smartagritest.HumidityResponse)) {
      return super.equals(obj);
    }
    com.example.smartagritest.HumidityResponse other = (com.example.smartagritest.HumidityResponse) obj;

    boolean result = true;
    result = result && (hasHumidityReading() == other.hasHumidityReading());
    if (hasHumidityReading()) {
      result = result && getHumidityReading()
          .equals(other.getHumidityReading());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHumidityReading()) {
      hash = (37 * hash) + HUMIDITY_READING_FIELD_NUMBER;
      hash = (53 * hash) + getHumidityReading().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.smartagritest.HumidityResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.HumidityResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.HumidityResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.HumidityResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.HumidityResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.HumidityResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.HumidityResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.HumidityResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartagritest.HumidityResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.HumidityResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartagritest.HumidityResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.HumidityResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.smartagritest.HumidityResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.smartagritest.HumidityResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.smartagritest.HumidityResponse)
      com.example.smartagritest.HumidityResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_HumidityResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_HumidityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.smartagritest.HumidityResponse.class, com.example.smartagritest.HumidityResponse.Builder.class);
    }

    // Construct using com.example.smartagritest.HumidityResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (humidityReadingBuilder_ == null) {
        humidityReading_ = null;
      } else {
        humidityReading_ = null;
        humidityReadingBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_HumidityResponse_descriptor;
    }

    @java.lang.Override
    public com.example.smartagritest.HumidityResponse getDefaultInstanceForType() {
      return com.example.smartagritest.HumidityResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.smartagritest.HumidityResponse build() {
      com.example.smartagritest.HumidityResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.smartagritest.HumidityResponse buildPartial() {
      com.example.smartagritest.HumidityResponse result = new com.example.smartagritest.HumidityResponse(this);
      if (humidityReadingBuilder_ == null) {
        result.humidityReading_ = humidityReading_;
      } else {
        result.humidityReading_ = humidityReadingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.smartagritest.HumidityResponse) {
        return mergeFrom((com.example.smartagritest.HumidityResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.smartagritest.HumidityResponse other) {
      if (other == com.example.smartagritest.HumidityResponse.getDefaultInstance()) return this;
      if (other.hasHumidityReading()) {
        mergeHumidityReading(other.getHumidityReading());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.smartagritest.HumidityResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.smartagritest.HumidityResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.smartagritest.HumidityReading humidityReading_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.smartagritest.HumidityReading, com.example.smartagritest.HumidityReading.Builder, com.example.smartagritest.HumidityReadingOrBuilder> humidityReadingBuilder_;
    /**
     * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
     */
    public boolean hasHumidityReading() {
      return humidityReadingBuilder_ != null || humidityReading_ != null;
    }
    /**
     * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
     */
    public com.example.smartagritest.HumidityReading getHumidityReading() {
      if (humidityReadingBuilder_ == null) {
        return humidityReading_ == null ? com.example.smartagritest.HumidityReading.getDefaultInstance() : humidityReading_;
      } else {
        return humidityReadingBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
     */
    public Builder setHumidityReading(com.example.smartagritest.HumidityReading value) {
      if (humidityReadingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        humidityReading_ = value;
        onChanged();
      } else {
        humidityReadingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
     */
    public Builder setHumidityReading(
        com.example.smartagritest.HumidityReading.Builder builderForValue) {
      if (humidityReadingBuilder_ == null) {
        humidityReading_ = builderForValue.build();
        onChanged();
      } else {
        humidityReadingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
     */
    public Builder mergeHumidityReading(com.example.smartagritest.HumidityReading value) {
      if (humidityReadingBuilder_ == null) {
        if (humidityReading_ != null) {
          humidityReading_ =
            com.example.smartagritest.HumidityReading.newBuilder(humidityReading_).mergeFrom(value).buildPartial();
        } else {
          humidityReading_ = value;
        }
        onChanged();
      } else {
        humidityReadingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
     */
    public Builder clearHumidityReading() {
      if (humidityReadingBuilder_ == null) {
        humidityReading_ = null;
        onChanged();
      } else {
        humidityReading_ = null;
        humidityReadingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
     */
    public com.example.smartagritest.HumidityReading.Builder getHumidityReadingBuilder() {
      
      onChanged();
      return getHumidityReadingFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
     */
    public com.example.smartagritest.HumidityReadingOrBuilder getHumidityReadingOrBuilder() {
      if (humidityReadingBuilder_ != null) {
        return humidityReadingBuilder_.getMessageOrBuilder();
      } else {
        return humidityReading_ == null ?
            com.example.smartagritest.HumidityReading.getDefaultInstance() : humidityReading_;
      }
    }
    /**
     * <code>.com.example.smartagritest.HumidityReading humidity_reading = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.smartagritest.HumidityReading, com.example.smartagritest.HumidityReading.Builder, com.example.smartagritest.HumidityReadingOrBuilder> 
        getHumidityReadingFieldBuilder() {
      if (humidityReadingBuilder_ == null) {
        humidityReadingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.smartagritest.HumidityReading, com.example.smartagritest.HumidityReading.Builder, com.example.smartagritest.HumidityReadingOrBuilder>(
                getHumidityReading(),
                getParentForChildren(),
                isClean());
        humidityReading_ = null;
      }
      return humidityReadingBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.smartagritest.HumidityResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.smartagritest.HumidityResponse)
  private static final com.example.smartagritest.HumidityResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.smartagritest.HumidityResponse();
  }

  public static com.example.smartagritest.HumidityResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HumidityResponse>
      PARSER = new com.google.protobuf.AbstractParser<HumidityResponse>() {
    @java.lang.Override
    public HumidityResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HumidityResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HumidityResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HumidityResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.smartagritest.HumidityResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

