// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

/**
 * Protobuf type {@code com.example.smartagritest.LightLevelResponse}
 */
public  final class LightLevelResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.smartagritest.LightLevelResponse)
    LightLevelResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LightLevelResponse.newBuilder() to construct.
  private LightLevelResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LightLevelResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LightLevelResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.example.smartagritest.LightLevelReading.Builder subBuilder = null;
            if (lightLevelReading_ != null) {
              subBuilder = lightLevelReading_.toBuilder();
            }
            lightLevelReading_ = input.readMessage(com.example.smartagritest.LightLevelReading.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lightLevelReading_);
              lightLevelReading_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_LightLevelResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_LightLevelResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.smartagritest.LightLevelResponse.class, com.example.smartagritest.LightLevelResponse.Builder.class);
  }

  public static final int LIGHT_LEVEL_READING_FIELD_NUMBER = 1;
  private com.example.smartagritest.LightLevelReading lightLevelReading_;
  /**
   * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
   */
  public boolean hasLightLevelReading() {
    return lightLevelReading_ != null;
  }
  /**
   * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
   */
  public com.example.smartagritest.LightLevelReading getLightLevelReading() {
    return lightLevelReading_ == null ? com.example.smartagritest.LightLevelReading.getDefaultInstance() : lightLevelReading_;
  }
  /**
   * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
   */
  public com.example.smartagritest.LightLevelReadingOrBuilder getLightLevelReadingOrBuilder() {
    return getLightLevelReading();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lightLevelReading_ != null) {
      output.writeMessage(1, getLightLevelReading());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lightLevelReading_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLightLevelReading());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.smartagritest.LightLevelResponse)) {
      return super.equals(obj);
    }
    com.example.smartagritest.LightLevelResponse other = (com.example.smartagritest.LightLevelResponse) obj;

    boolean result = true;
    result = result && (hasLightLevelReading() == other.hasLightLevelReading());
    if (hasLightLevelReading()) {
      result = result && getLightLevelReading()
          .equals(other.getLightLevelReading());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLightLevelReading()) {
      hash = (37 * hash) + LIGHT_LEVEL_READING_FIELD_NUMBER;
      hash = (53 * hash) + getLightLevelReading().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.smartagritest.LightLevelResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.LightLevelResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.LightLevelResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.LightLevelResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.LightLevelResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.LightLevelResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.LightLevelResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.LightLevelResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartagritest.LightLevelResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.LightLevelResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartagritest.LightLevelResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.LightLevelResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.smartagritest.LightLevelResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.smartagritest.LightLevelResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.smartagritest.LightLevelResponse)
      com.example.smartagritest.LightLevelResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_LightLevelResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_LightLevelResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.smartagritest.LightLevelResponse.class, com.example.smartagritest.LightLevelResponse.Builder.class);
    }

    // Construct using com.example.smartagritest.LightLevelResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (lightLevelReadingBuilder_ == null) {
        lightLevelReading_ = null;
      } else {
        lightLevelReading_ = null;
        lightLevelReadingBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_LightLevelResponse_descriptor;
    }

    @java.lang.Override
    public com.example.smartagritest.LightLevelResponse getDefaultInstanceForType() {
      return com.example.smartagritest.LightLevelResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.smartagritest.LightLevelResponse build() {
      com.example.smartagritest.LightLevelResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.smartagritest.LightLevelResponse buildPartial() {
      com.example.smartagritest.LightLevelResponse result = new com.example.smartagritest.LightLevelResponse(this);
      if (lightLevelReadingBuilder_ == null) {
        result.lightLevelReading_ = lightLevelReading_;
      } else {
        result.lightLevelReading_ = lightLevelReadingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.smartagritest.LightLevelResponse) {
        return mergeFrom((com.example.smartagritest.LightLevelResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.smartagritest.LightLevelResponse other) {
      if (other == com.example.smartagritest.LightLevelResponse.getDefaultInstance()) return this;
      if (other.hasLightLevelReading()) {
        mergeLightLevelReading(other.getLightLevelReading());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.smartagritest.LightLevelResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.smartagritest.LightLevelResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.smartagritest.LightLevelReading lightLevelReading_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.smartagritest.LightLevelReading, com.example.smartagritest.LightLevelReading.Builder, com.example.smartagritest.LightLevelReadingOrBuilder> lightLevelReadingBuilder_;
    /**
     * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
     */
    public boolean hasLightLevelReading() {
      return lightLevelReadingBuilder_ != null || lightLevelReading_ != null;
    }
    /**
     * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
     */
    public com.example.smartagritest.LightLevelReading getLightLevelReading() {
      if (lightLevelReadingBuilder_ == null) {
        return lightLevelReading_ == null ? com.example.smartagritest.LightLevelReading.getDefaultInstance() : lightLevelReading_;
      } else {
        return lightLevelReadingBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
     */
    public Builder setLightLevelReading(com.example.smartagritest.LightLevelReading value) {
      if (lightLevelReadingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lightLevelReading_ = value;
        onChanged();
      } else {
        lightLevelReadingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
     */
    public Builder setLightLevelReading(
        com.example.smartagritest.LightLevelReading.Builder builderForValue) {
      if (lightLevelReadingBuilder_ == null) {
        lightLevelReading_ = builderForValue.build();
        onChanged();
      } else {
        lightLevelReadingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
     */
    public Builder mergeLightLevelReading(com.example.smartagritest.LightLevelReading value) {
      if (lightLevelReadingBuilder_ == null) {
        if (lightLevelReading_ != null) {
          lightLevelReading_ =
            com.example.smartagritest.LightLevelReading.newBuilder(lightLevelReading_).mergeFrom(value).buildPartial();
        } else {
          lightLevelReading_ = value;
        }
        onChanged();
      } else {
        lightLevelReadingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
     */
    public Builder clearLightLevelReading() {
      if (lightLevelReadingBuilder_ == null) {
        lightLevelReading_ = null;
        onChanged();
      } else {
        lightLevelReading_ = null;
        lightLevelReadingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
     */
    public com.example.smartagritest.LightLevelReading.Builder getLightLevelReadingBuilder() {
      
      onChanged();
      return getLightLevelReadingFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
     */
    public com.example.smartagritest.LightLevelReadingOrBuilder getLightLevelReadingOrBuilder() {
      if (lightLevelReadingBuilder_ != null) {
        return lightLevelReadingBuilder_.getMessageOrBuilder();
      } else {
        return lightLevelReading_ == null ?
            com.example.smartagritest.LightLevelReading.getDefaultInstance() : lightLevelReading_;
      }
    }
    /**
     * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.smartagritest.LightLevelReading, com.example.smartagritest.LightLevelReading.Builder, com.example.smartagritest.LightLevelReadingOrBuilder> 
        getLightLevelReadingFieldBuilder() {
      if (lightLevelReadingBuilder_ == null) {
        lightLevelReadingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.smartagritest.LightLevelReading, com.example.smartagritest.LightLevelReading.Builder, com.example.smartagritest.LightLevelReadingOrBuilder>(
                getLightLevelReading(),
                getParentForChildren(),
                isClean());
        lightLevelReading_ = null;
      }
      return lightLevelReadingBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.smartagritest.LightLevelResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.smartagritest.LightLevelResponse)
  private static final com.example.smartagritest.LightLevelResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.smartagritest.LightLevelResponse();
  }

  public static com.example.smartagritest.LightLevelResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LightLevelResponse>
      PARSER = new com.google.protobuf.AbstractParser<LightLevelResponse>() {
    @java.lang.Override
    public LightLevelResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LightLevelResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LightLevelResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LightLevelResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.smartagritest.LightLevelResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

