// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public interface LightLevelReadingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.LightLevelReading)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double light_level = 1;</code>
   */
  double getLightLevel();

  /**
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();
}
