// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public interface LightLevelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.LightLevelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
   */
  boolean hasLightLevelReading();
  /**
   * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
   */
  com.example.smartagritest.LightLevelReading getLightLevelReading();
  /**
   * <code>.com.example.smartagritest.LightLevelReading light_level_reading = 1;</code>
   */
  com.example.smartagritest.LightLevelReadingOrBuilder getLightLevelReadingOrBuilder();
}
