// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livestockmanagement.proto

package com.example.smartagritest;

public interface LiveStockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.LiveStock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string birth_date = 3;</code>
   */
  java.lang.String getBirthDate();
  /**
   * <code>string birth_date = 3;</code>
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>int32 quantity = 4;</code>
   */
  int getQuantity();
}
