// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cropmanagementservice.proto

package com.example.smartagritest;

public interface PlantCropRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.PlantCropRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string seed_type = 2;</code>
   */
  java.lang.String getSeedType();
  /**
   * <code>string seed_type = 2;</code>
   */
  com.google.protobuf.ByteString
      getSeedTypeBytes();

  /**
   * <code>string planting_date = 3;</code>
   */
  java.lang.String getPlantingDate();
  /**
   * <code>string planting_date = 3;</code>
   */
  com.google.protobuf.ByteString
      getPlantingDateBytes();
}
