// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public final class SensorServiceProto {
  private SensorServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_TemperatureReading_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_TemperatureReading_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_HumidityReading_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_HumidityReading_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_LightLevelReading_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_LightLevelReading_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_SensorConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_SensorConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_AlertThreshold_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_AlertThreshold_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_TemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_HumidityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_HumidityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_HumidityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_HumidityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_LightLevelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_LightLevelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_LightLevelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_LightLevelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_SensorConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_SensorConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_smartagritest_AlertThresholdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_smartagritest_AlertThresholdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023sensorservice.proto\022\031com.example.smart" +
      "agritest\"<\n\022TemperatureReading\022\023\n\013temper" +
      "ature\030\001 \001(\001\022\021\n\ttimestamp\030\002 \001(\003\"6\n\017Humidi" +
      "tyReading\022\020\n\010humidity\030\001 \001(\001\022\021\n\ttimestamp" +
      "\030\002 \001(\003\";\n\021LightLevelReading\022\023\n\013light_lev" +
      "el\030\001 \001(\001\022\021\n\ttimestamp\030\002 \001(\003\"Y\n\023SensorCon" +
      "figuration\022\023\n\013sensor_name\030\001 \001(\t\022\030\n\020polli" +
      "ng_interval\030\002 \001(\005\022\023\n\013sensitivity\030\003 \001(\001\"8" +
      "\n\016AlertThreshold\022\023\n\013sensor_name\030\001 \001(\t\022\021\n" +
      "\tthreshold\030\002 \001(\001\")\n\022TemperatureRequest\022\023" +
      "\n\013sensor_name\030\001 \001(\t\"a\n\023TemperatureRespon" +
      "se\022J\n\023temperature_reading\030\001 \001(\0132-.com.ex" +
      "ample.smartagritest.TemperatureReading\"&" +
      "\n\017HumidityRequest\022\023\n\013sensor_name\030\001 \001(\t\"X" +
      "\n\020HumidityResponse\022D\n\020humidity_reading\030\001" +
      " \001(\0132*.com.example.smartagritest.Humidit" +
      "yReading\"(\n\021LightLevelRequest\022\023\n\013sensor_" +
      "name\030\001 \001(\t\"_\n\022LightLevelResponse\022I\n\023ligh" +
      "t_level_reading\030\001 \001(\0132,.com.example.smar" +
      "tagritest.LightLevelReading\"-\n\033SensorCon" +
      "figurationResponse\022\016\n\006status\030\001 \001(\t\"(\n\026Al" +
      "ertThresholdResponse\022\016\n\006status\030\001 \001(\t2\326\004\n" +
      "\rSensorService\022q\n\016getTemperature\022-.com.e" +
      "xample.smartagritest.TemperatureRequest\032" +
      "..com.example.smartagritest.TemperatureR" +
      "esponse\"\000\022h\n\013getHumidity\022*.com.example.s" +
      "martagritest.HumidityRequest\032+.com.examp" +
      "le.smartagritest.HumidityResponse\"\000\022n\n\rg" +
      "etLightLevel\022,.com.example.smartagritest" +
      ".LightLevelRequest\032-.com.example.smartag" +
      "ritest.LightLevelResponse\"\000\022\202\001\n\026setSenso" +
      "rConfiguration\022..com.example.smartagrite" +
      "st.SensorConfiguration\0326.com.example.sma" +
      "rtagritest.SensorConfigurationResponse\"\000" +
      "\022s\n\021setAlertThreshold\022).com.example.smar" +
      "tagritest.AlertThreshold\0321.com.example.s" +
      "martagritest.AlertThresholdResponse\"\000B1\n" +
      "\031com.example.smartagritestB\022SensorServic" +
      "eProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_smartagritest_TemperatureReading_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_smartagritest_TemperatureReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_TemperatureReading_descriptor,
        new java.lang.String[] { "Temperature", "Timestamp", });
    internal_static_com_example_smartagritest_HumidityReading_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_smartagritest_HumidityReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_HumidityReading_descriptor,
        new java.lang.String[] { "Humidity", "Timestamp", });
    internal_static_com_example_smartagritest_LightLevelReading_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_smartagritest_LightLevelReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_LightLevelReading_descriptor,
        new java.lang.String[] { "LightLevel", "Timestamp", });
    internal_static_com_example_smartagritest_SensorConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_smartagritest_SensorConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_SensorConfiguration_descriptor,
        new java.lang.String[] { "SensorName", "PollingInterval", "Sensitivity", });
    internal_static_com_example_smartagritest_AlertThreshold_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_smartagritest_AlertThreshold_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_AlertThreshold_descriptor,
        new java.lang.String[] { "SensorName", "Threshold", });
    internal_static_com_example_smartagritest_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_smartagritest_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_TemperatureRequest_descriptor,
        new java.lang.String[] { "SensorName", });
    internal_static_com_example_smartagritest_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_example_smartagritest_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_TemperatureResponse_descriptor,
        new java.lang.String[] { "TemperatureReading", });
    internal_static_com_example_smartagritest_HumidityRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_example_smartagritest_HumidityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_HumidityRequest_descriptor,
        new java.lang.String[] { "SensorName", });
    internal_static_com_example_smartagritest_HumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_example_smartagritest_HumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_HumidityResponse_descriptor,
        new java.lang.String[] { "HumidityReading", });
    internal_static_com_example_smartagritest_LightLevelRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_example_smartagritest_LightLevelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_LightLevelRequest_descriptor,
        new java.lang.String[] { "SensorName", });
    internal_static_com_example_smartagritest_LightLevelResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_example_smartagritest_LightLevelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_LightLevelResponse_descriptor,
        new java.lang.String[] { "LightLevelReading", });
    internal_static_com_example_smartagritest_SensorConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_example_smartagritest_SensorConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_SensorConfigurationResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_example_smartagritest_AlertThresholdResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_example_smartagritest_AlertThresholdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_smartagritest_AlertThresholdResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
