// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public interface SensorConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.SensorConfiguration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_name = 1;</code>
   */
  java.lang.String getSensorName();
  /**
   * <code>string sensor_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorNameBytes();

  /**
   * <code>int32 polling_interval = 2;</code>
   */
  int getPollingInterval();

  /**
   * <code>double sensitivity = 3;</code>
   */
  double getSensitivity();
}
