// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public interface TemperatureReadingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.TemperatureReading)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();

  /**
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();
}
