// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
   */
  boolean hasTemperatureReading();
  /**
   * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
   */
  com.example.smartagritest.TemperatureReading getTemperatureReading();
  /**
   * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
   */
  com.example.smartagritest.TemperatureReadingOrBuilder getTemperatureReadingOrBuilder();
}
