// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorservice.proto

package com.example.smartagritest;

/**
 * Protobuf type {@code com.example.smartagritest.TemperatureResponse}
 */
public  final class TemperatureResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.smartagritest.TemperatureResponse)
    TemperatureResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TemperatureResponse.newBuilder() to construct.
  private TemperatureResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TemperatureResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TemperatureResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.example.smartagritest.TemperatureReading.Builder subBuilder = null;
            if (temperatureReading_ != null) {
              subBuilder = temperatureReading_.toBuilder();
            }
            temperatureReading_ = input.readMessage(com.example.smartagritest.TemperatureReading.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(temperatureReading_);
              temperatureReading_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_TemperatureResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_TemperatureResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.smartagritest.TemperatureResponse.class, com.example.smartagritest.TemperatureResponse.Builder.class);
  }

  public static final int TEMPERATURE_READING_FIELD_NUMBER = 1;
  private com.example.smartagritest.TemperatureReading temperatureReading_;
  /**
   * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
   */
  public boolean hasTemperatureReading() {
    return temperatureReading_ != null;
  }
  /**
   * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
   */
  public com.example.smartagritest.TemperatureReading getTemperatureReading() {
    return temperatureReading_ == null ? com.example.smartagritest.TemperatureReading.getDefaultInstance() : temperatureReading_;
  }
  /**
   * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
   */
  public com.example.smartagritest.TemperatureReadingOrBuilder getTemperatureReadingOrBuilder() {
    return getTemperatureReading();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (temperatureReading_ != null) {
      output.writeMessage(1, getTemperatureReading());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (temperatureReading_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTemperatureReading());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.smartagritest.TemperatureResponse)) {
      return super.equals(obj);
    }
    com.example.smartagritest.TemperatureResponse other = (com.example.smartagritest.TemperatureResponse) obj;

    boolean result = true;
    result = result && (hasTemperatureReading() == other.hasTemperatureReading());
    if (hasTemperatureReading()) {
      result = result && getTemperatureReading()
          .equals(other.getTemperatureReading());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTemperatureReading()) {
      hash = (37 * hash) + TEMPERATURE_READING_FIELD_NUMBER;
      hash = (53 * hash) + getTemperatureReading().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.smartagritest.TemperatureResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.TemperatureResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.TemperatureResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.TemperatureResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.TemperatureResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartagritest.TemperatureResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartagritest.TemperatureResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.TemperatureResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartagritest.TemperatureResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.TemperatureResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartagritest.TemperatureResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartagritest.TemperatureResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.smartagritest.TemperatureResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.smartagritest.TemperatureResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.smartagritest.TemperatureResponse)
      com.example.smartagritest.TemperatureResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_TemperatureResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_TemperatureResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.smartagritest.TemperatureResponse.class, com.example.smartagritest.TemperatureResponse.Builder.class);
    }

    // Construct using com.example.smartagritest.TemperatureResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (temperatureReadingBuilder_ == null) {
        temperatureReading_ = null;
      } else {
        temperatureReading_ = null;
        temperatureReadingBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.smartagritest.SensorServiceProto.internal_static_com_example_smartagritest_TemperatureResponse_descriptor;
    }

    @java.lang.Override
    public com.example.smartagritest.TemperatureResponse getDefaultInstanceForType() {
      return com.example.smartagritest.TemperatureResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.smartagritest.TemperatureResponse build() {
      com.example.smartagritest.TemperatureResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.smartagritest.TemperatureResponse buildPartial() {
      com.example.smartagritest.TemperatureResponse result = new com.example.smartagritest.TemperatureResponse(this);
      if (temperatureReadingBuilder_ == null) {
        result.temperatureReading_ = temperatureReading_;
      } else {
        result.temperatureReading_ = temperatureReadingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.smartagritest.TemperatureResponse) {
        return mergeFrom((com.example.smartagritest.TemperatureResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.smartagritest.TemperatureResponse other) {
      if (other == com.example.smartagritest.TemperatureResponse.getDefaultInstance()) return this;
      if (other.hasTemperatureReading()) {
        mergeTemperatureReading(other.getTemperatureReading());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.smartagritest.TemperatureResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.smartagritest.TemperatureResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.smartagritest.TemperatureReading temperatureReading_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.smartagritest.TemperatureReading, com.example.smartagritest.TemperatureReading.Builder, com.example.smartagritest.TemperatureReadingOrBuilder> temperatureReadingBuilder_;
    /**
     * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
     */
    public boolean hasTemperatureReading() {
      return temperatureReadingBuilder_ != null || temperatureReading_ != null;
    }
    /**
     * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
     */
    public com.example.smartagritest.TemperatureReading getTemperatureReading() {
      if (temperatureReadingBuilder_ == null) {
        return temperatureReading_ == null ? com.example.smartagritest.TemperatureReading.getDefaultInstance() : temperatureReading_;
      } else {
        return temperatureReadingBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
     */
    public Builder setTemperatureReading(com.example.smartagritest.TemperatureReading value) {
      if (temperatureReadingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        temperatureReading_ = value;
        onChanged();
      } else {
        temperatureReadingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
     */
    public Builder setTemperatureReading(
        com.example.smartagritest.TemperatureReading.Builder builderForValue) {
      if (temperatureReadingBuilder_ == null) {
        temperatureReading_ = builderForValue.build();
        onChanged();
      } else {
        temperatureReadingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
     */
    public Builder mergeTemperatureReading(com.example.smartagritest.TemperatureReading value) {
      if (temperatureReadingBuilder_ == null) {
        if (temperatureReading_ != null) {
          temperatureReading_ =
            com.example.smartagritest.TemperatureReading.newBuilder(temperatureReading_).mergeFrom(value).buildPartial();
        } else {
          temperatureReading_ = value;
        }
        onChanged();
      } else {
        temperatureReadingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
     */
    public Builder clearTemperatureReading() {
      if (temperatureReadingBuilder_ == null) {
        temperatureReading_ = null;
        onChanged();
      } else {
        temperatureReading_ = null;
        temperatureReadingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
     */
    public com.example.smartagritest.TemperatureReading.Builder getTemperatureReadingBuilder() {
      
      onChanged();
      return getTemperatureReadingFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
     */
    public com.example.smartagritest.TemperatureReadingOrBuilder getTemperatureReadingOrBuilder() {
      if (temperatureReadingBuilder_ != null) {
        return temperatureReadingBuilder_.getMessageOrBuilder();
      } else {
        return temperatureReading_ == null ?
            com.example.smartagritest.TemperatureReading.getDefaultInstance() : temperatureReading_;
      }
    }
    /**
     * <code>.com.example.smartagritest.TemperatureReading temperature_reading = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.smartagritest.TemperatureReading, com.example.smartagritest.TemperatureReading.Builder, com.example.smartagritest.TemperatureReadingOrBuilder> 
        getTemperatureReadingFieldBuilder() {
      if (temperatureReadingBuilder_ == null) {
        temperatureReadingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.smartagritest.TemperatureReading, com.example.smartagritest.TemperatureReading.Builder, com.example.smartagritest.TemperatureReadingOrBuilder>(
                getTemperatureReading(),
                getParentForChildren(),
                isClean());
        temperatureReading_ = null;
      }
      return temperatureReadingBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.smartagritest.TemperatureResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.smartagritest.TemperatureResponse)
  private static final com.example.smartagritest.TemperatureResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.smartagritest.TemperatureResponse();
  }

  public static com.example.smartagritest.TemperatureResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TemperatureResponse>
      PARSER = new com.google.protobuf.AbstractParser<TemperatureResponse>() {
    @java.lang.Override
    public TemperatureResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TemperatureResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TemperatureResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TemperatureResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.smartagritest.TemperatureResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

