// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livestockmanagement.proto

package com.example.smartagritest;

public interface UpdateLiveStockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.UpdateLiveStockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
   */
  boolean hasLiveStock();
  /**
   * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
   */
  com.example.smartagritest.LiveStock getLiveStock();
  /**
   * <code>.com.example.smartagritest.LiveStock liveStock = 1;</code>
   */
  com.example.smartagritest.LiveStockOrBuilder getLiveStockOrBuilder();
}
