// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cropmanagementservice.proto

package com.example.smartagritest;

public interface UpdateCropRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.smartagritest.UpdateCropRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string new_type = 2;</code>
   */
  java.lang.String getNewType();
  /**
   * <code>string new_type = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewTypeBytes();

  /**
   * <code>string new_planting_date = 3;</code>
   */
  java.lang.String getNewPlantingDate();
  /**
   * <code>string new_planting_date = 3;</code>
   */
  com.google.protobuf.ByteString
      getNewPlantingDateBytes();
}
